title: "Security Blog "
description: "Malware Reports, IoCs, and more"
theme: minima
# Feel free to adjust or add more config settings here

# If you want to use categories or collections later, you can add them here.
# For now, keep it minimal.
