title: " Cybersecurity Blog"
description: "Malware Reports, IoCs, Threat Analysis, etc."

# This tells GitHub Pages to fetch the Hacker theme from the pages-themes repo.
remote_theme: pages-themes/hacker@v0.2.0

# This plugin is required for remote themes to work on GitHub Pages.
plugins:
  - jekyll-remote-theme

# Optional: You can add or tweak other Jekyll settings here, e.g.:
# markdown: kramdown
# exclude:
#   - README.md
